# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranslatorMain(object):
    def setupUi(self, TranslatorMain):
        TranslatorMain.setObjectName("TranslatorMain")
        TranslatorMain.resize(503, 304)
        self.centralwidget = QtWidgets.QWidget(TranslatorMain)
        self.centralwidget.setObjectName("centralwidget")
        self.gb_do = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_do.setGeometry(QtCore.QRect(10, 100, 481, 151))
        self.gb_do.setObjectName("gb_do")
        self.pbtn_translate = QtWidgets.QPushButton(self.gb_do)
        self.pbtn_translate.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pbtn_translate.setObjectName("pbtn_translate")
        self.pte_result = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_result.setGeometry(QtCore.QRect(10, 20, 481, 71))
        self.pte_result.setObjectName("pte_result")
        TranslatorMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TranslatorMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 503, 23))
        self.menubar.setObjectName("menubar")
        TranslatorMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TranslatorMain)
        self.statusbar.setObjectName("statusbar")
        TranslatorMain.setStatusBar(self.statusbar)

        self.retranslateUi(TranslatorMain)
        QtCore.QMetaObject.connectSlotsByName(TranslatorMain)

    def retranslateUi(self, TranslatorMain):
        _translate = QtCore.QCoreApplication.translate
        TranslatorMain.setWindowTitle(_translate("TranslatorMain", "O2T Translator"))
        self.gb_do.setTitle(_translate("TranslatorMain", "操作"))
        self.pbtn_translate.setText(_translate("TranslatorMain", "翻译"))
